### ISSUE TITLE
This plugin does not implement the Moodle privacy API

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kiklop74/moodle-local_fancybox3#1]
This plugin does not implement the Moodle privacy API. If this plugin stores any personal data it will not be able to be exported or deleted through Moodle's privacy system.

Please see https://docs.moodle.org/dev/Privacy_API 

![fancybox does not implement the moodle privacy api](https://user-images.githubusercontent.com/2671923/44225415-1d41a900-a153-11e8-9376-d64040a6e2df.png)

Thanks in advance.

**Comment by kiklop74** [comment]
This plugin does nothing with any kind of data. It just serves as wrapper for third-party javascript library.
In any case this is now implemented.

**Comment by germanvaleroelizondo** [comment]
Thanks
